### ISSUE TITLE
About the missing files

### ISSUE THREAD

**Issue by HyperbolicCurve** [ouenal/concretenet#1]
Hello~, I want to know what's the ModelFactory in line 17, eval.py

**Comment by ouenal** [comment]
I intended for it to be similar to `DatasetFactory`, which only provides a link to the correct model class. However, since we only release one model, I simplified `train.py` by bypassing the factory but must have overlooked this in the `eval.py` script.

To fix the issue, you can make the following changes:

- Replace Line 17 with: 
```python
  from network.concretenet import ConcreteNet
```
- Replace Line 49 with:
```python
self.model = ConcreteNet(**config['model']).cuda()
```

This should resolve the issue. Let me know if it works, and I’ll push the changes to the repo.
